repos:
      - repo: https://github.com/astral-sh/ruff-pre-commit
        rev: v0.3.5
        hooks:
          # Run the Ruff linter.
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]
          # Run the Ruff formatter.
          - id: ruff-format

      - repo: https://github.com/python-poetry/poetry
        rev: "1.8.2"
        hooks:
          - id: poetry-check # check validity of pyproject.toml
          - id: poetry-lock # make sure lock file is up-to-date