[tool.poetry]
name = "spotify-stats"
version = "0.1.0"
description = ""
authors = ["Jakob Klotz <88966745+kometenmelodie@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^1.5.0"
spotipy = "^2.20.0"
requests = "^2.28.1"
pillow = "^9.3.0"
flask = "^2.2.2"
python-dotenv = "^0.21.0"
plotly = "^5.11.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
